/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.donorpkg;

import business.commonUtils.ValidateDateOfBirth;
import business.commonUtils.ValidateEmailTextField;
import business.commonUtils.ValidateNumbers;
import business.commonUtils.ValidatePhoneNumber;
import business.commonUtils.ValidateStrings;
import business.commonUtils.Validation;
import business.personpkg.Person;
import business.userAccountpkg.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class ViewMyProfile extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Person person;
    
    /**
     * Creates new form ViewMyProfile
     */
    public ViewMyProfile(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        person = userAccount.getPerson();
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        dfnametxt.setText(person.getName());
      if(person.getDob()!=null && person.getAddress1()!=null && person.getTown()!=null 
                && person.getZipCode()!=null && person.getOccupation()!=null &&
                person.getEmailId()!=null && person.getPhoneNumber()!=null
                )
       {
        ddobtxtt.setText(dateFormat.format(person.getDob()));
        addddtxt.setText(person.getAddress1());
        txttownnn.setText(person.getTown());
        txtttzipcode.setText(person.getZipCode());
        txtttoccu.setText(person.getOccupation());
        txtttemailaddd.setText(person.getEmailId());
        txttmobile_numberr.setText(person.getPhoneNumber());
        }
        addInputVerifiers();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth();
        int h = getHeight();
        
        Color c1 = new Color(234,32,94);
        Color c2 = Color.white;
     
        GradientPaint gp = new GradientPaint(w/4, 0, c2, w/4, h, c1);
        setOpaque( false );
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
        setOpaque( true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorName = new javax.swing.JLabel();
        dfnametxt = new javax.swing.JTextField();
        txtttzipcode = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JLabel();
        occupation = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        txtttoccu = new javax.swing.JTextField();
        addddtxt = new javax.swing.JTextField();
        emailID = new javax.swing.JLabel();
        town = new javax.swing.JLabel();
        txtttemailaddd = new javax.swing.JTextField();
        txttownnn = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JLabel();
        zipCode = new javax.swing.JLabel();
        txttmobile_numberr = new javax.swing.JTextField();
        ddobtxtt = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        btnupdateee = new javax.swing.JButton();

        donorName.setText("Full Name:");

        dfnametxt.setEditable(false);
        dfnametxt.setEnabled(false);

        txtttzipcode.setEditable(false);
        txtttzipcode.setEnabled(false);

        dateOfBirth.setText("Date Of Birth (MM/DD/YYYY):");

        occupation.setText("Occupation:");

        address.setText("Address: ");

        txtttoccu.setEditable(false);
        txtttoccu.setEnabled(false);

        addddtxt.setEditable(false);
        addddtxt.setEnabled(false);

        emailID.setText("Email Address:");

        town.setText("Town/City: ");

        txtttemailaddd.setEditable(false);
        txtttemailaddd.setEnabled(false);

        txttownnn.setEditable(false);
        txttownnn.setEnabled(false);

        phoneNumber.setText("Phone Number:");

        zipCode.setText("Zip Code:");

        txttmobile_numberr.setEditable(false);
        txttmobile_numberr.setEnabled(false);

        ddobtxtt.setEditable(false);
        ddobtxtt.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        jLabel6.setText("View / Update Profile");

        backJButton.setText(" back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        saveJButton.setText("Save");
        saveJButton.setEnabled(false);
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        btnupdateee.setText("Update");
        btnupdateee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(backJButton)
                        .addGap(240, 240, 240)
                        .addComponent(btnupdateee)
                        .addGap(33, 33, 33)
                        .addComponent(saveJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(dfnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(town))
                                    .addComponent(occupation)
                                    .addComponent(emailID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(donorName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txttmobile_numberr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ddobtxtt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtttzipcode, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttownnn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtttoccu, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtttemailaddd, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addddtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donorName)
                    .addComponent(dfnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfBirth)
                    .addComponent(ddobtxtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address)
                    .addComponent(addddtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(town)
                    .addComponent(txttownnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(occupation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtttoccu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailID)
                    .addComponent(txtttemailaddd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtttzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttmobile_numberr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(btnupdateee)
                    .addComponent(saveJButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
       
    private void addInputVerifiers() {
          
        InputVerifier stringValidation = new ValidateStrings();
        dfnametxt.setInputVerifier(stringValidation);
        addddtxt.setInputVerifier(stringValidation);
        txttownnn.setInputVerifier(stringValidation);
        txtttoccu.setInputVerifier(stringValidation);
       
        InputVerifier dobValidtion = new ValidateDateOfBirth();
        ddobtxtt.setInputVerifier(dobValidtion);
        
        InputVerifier numberValidation = new ValidateNumbers();
        txtttzipcode.setInputVerifier(numberValidation);
        
           InputVerifier emailValidtion = new ValidateEmailTextField();
           txtttemailaddd.setInputVerifier(emailValidtion);
     
        
       InputVerifier phnumberValidation = new ValidatePhoneNumber();
        txttmobile_numberr.setInputVerifier(phnumberValidation);
        
    }
    
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed

        if(dfnametxt.getText()!= null && !dfnametxt.getText().isEmpty() &&
            addddtxt.getText()!=null && !addddtxt.getText().isEmpty() &&
            txttownnn.getText()!=null && !txttownnn.getText().isEmpty() &&
            txtttoccu.getText()!=null && !txtttoccu.getText().isEmpty() &&
            txtttemailaddd.getText()!=null && !txtttemailaddd.getText().isEmpty() &&
            txttmobile_numberr.getText()!=null && !txttmobile_numberr.getText().isEmpty() && 
            ddobtxtt.getText()!=null && !ddobtxtt.getText().trim().isEmpty() &&
            txtttzipcode.getText()!=null && !txtttzipcode.getText().trim().isEmpty() )
        {
            try
            {
              DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
              Date dateOfBirthVal  = dateFormat.parse(ddobtxtt.getText()) ;
                int age = Validation.calculateAge(dateOfBirthVal);
                if(age<=0 )
                {
                    JOptionPane.showMessageDialog(null, "Please enter valid age!","warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if((txttmobile_numberr.getText()).length()<10)
                {  
                    JOptionPane.showMessageDialog(null, "Please Enter valid phone number!","warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                person.setFirstName(dfnametxt.getText());
                person.setAddress1(addddtxt.getText());
                person.setTown(txttownnn.getText());
                person.setZipCode(txtttzipcode.getText());
                person.setOccupation(txtttoccu.getText());
                person.setDob(dateOfBirthVal);
                person.setPhoneNumber(txttmobile_numberr.getText());
                person.setEmailId(txtttemailaddd.getText());
                userAccount.setPerson(person);
            }
            catch(NumberFormatException nfe)
            {
                JOptionPane.showMessageDialog(this, "Please Enter valid details", "warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            catch(ParseException pe)
            {
                JOptionPane.showMessageDialog(this, "Please Enter valid date of birth", "warning",JOptionPane.WARNING_MESSAGE);
                 return;
            }

            
                JOptionPane.showMessageDialog(null, "Your Profile has been updated successfully", "success", JOptionPane.PLAIN_MESSAGE);
                btnupdateee.setEnabled(true);
                saveJButton.setEnabled(false);
                dfnametxt.setEnabled(false);
                ddobtxtt.setEnabled(false);
                addddtxt.setEnabled(false);
                txttownnn.setEnabled(false);
                txtttzipcode.setEnabled(false);
                txtttoccu.setEnabled(false);
                txtttemailaddd.setEnabled(false);
                txttmobile_numberr.setEnabled(false);
         }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Enter data in all the fields");
        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void btnupdateeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateeeActionPerformed

        dfnametxt.setEnabled(true);
        ddobtxtt.setEnabled(true);
        addddtxt.setEnabled(true);
        txttownnn.setEnabled(true);
        txtttzipcode.setEnabled(true);
        txtttoccu.setEnabled(true);
        txttmobile_numberr.setEnabled(true);
        txtttemailaddd.setEnabled(true);
        saveJButton.setEnabled(true);
        btnupdateee.setEnabled(false);
        dfnametxt.setEditable(true);
        ddobtxtt.setEditable(true);
        addddtxt.setEditable(true);
        txttownnn.setEditable(true);
        txtttzipcode.setEditable(true);
        txtttoccu.setEditable(true);
        txttmobile_numberr.setEditable(true);
        txtttemailaddd.setEditable(true);
    }//GEN-LAST:event_btnupdateeeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addddtxt;
    private javax.swing.JLabel address;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnupdateee;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JFormattedTextField ddobtxtt;
    private javax.swing.JTextField dfnametxt;
    private javax.swing.JLabel donorName;
    private javax.swing.JLabel emailID;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel occupation;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel town;
    private javax.swing.JTextField txttmobile_numberr;
    private javax.swing.JTextField txttownnn;
    private javax.swing.JTextField txtttemailaddd;
    private javax.swing.JTextField txtttoccu;
    private javax.swing.JTextField txtttzipcode;
    private javax.swing.JLabel zipCode;
    // End of variables declaration//GEN-END:variables
}
